// app/(legal)/terms/page.jsx
import Link from "next/link";

export const metadata = { title: "Terms of Service · Still" };

export default function TermsPage() {
  return (
    <div style={s.root}>
      <nav style={s.nav}>
        <Link href="/" style={s.logo}>🕯️ still</Link>
      </nav>
      <main style={s.main}>
        <h1 style={s.title}>Terms of Service</h1>
        <p style={s.date}>Last updated: January 2025</p>

        <Section title="1. Acceptance of Terms">
          By creating an account or using Still, you agree to these Terms of Service. If you do not agree, please do not use the service.
        </Section>

        <Section title="2. Description of Service">
          Still is an AI-powered tool that analyzes chat logs to generate a persona profile, allowing you to simulate conversations in a similar texting style. It is intended for personal entertainment only.
        </Section>

        <Section title="3. Eligibility">
          You must be at least 18 years old to use this service. By using Still, you represent that you are 18 or older.
        </Section>

        <Section title="4. Acceptable Use">
          You agree not to use Still to:
          <ul style={s.list}>
            <li>Harass, stalk, or harm any individual</li>
            <li>Impersonate another person for deceptive or malicious purposes</li>
            <li>Generate content that is illegal, abusive, or violates any third party's rights</li>
            <li>Circumvent any security measures or rate limits</li>
            <li>Upload chat logs belonging to others without their knowledge or consent</li>
          </ul>
        </Section>

        <Section title="5. Your Content">
          You retain ownership of any chat logs you upload. By using the service, you grant us a limited license to process that data solely to provide the service to you. We do not sell your data to third parties.
        </Section>

        <Section title="6. AI-Generated Content">
          The AI responses generated by Still are fictional and should not be mistaken for real communication from any person. We are not responsible for emotional distress, misunderstanding, or harm arising from use of AI-generated personas.
        </Section>

        <Section title="7. Mental Health Notice">
          Still is not a substitute for professional mental health support. If you are experiencing grief, depression, or difficulty processing a relationship, we encourage you to seek support from a qualified professional. Resources include:
          <ul style={s.list}>
            <li>Crisis Text Line: Text HOME to 741741</li>
            <li>SAMHSA Helpline: 1-800-662-4357</li>
            <li>BetterHelp.com for online therapy</li>
          </ul>
        </Section>

        <Section title="8. Account Termination">
          We reserve the right to suspend or terminate accounts that violate these Terms. You may delete your account at any time from your account settings.
        </Section>

        <Section title="9. Disclaimer of Warranties">
          Still is provided "as is" without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of AI-generated content.
        </Section>

        <Section title="10. Limitation of Liability">
          To the maximum extent permitted by law, Still shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service.
        </Section>

        <Section title="11. Changes to Terms">
          We may modify these terms at any time. Continued use of the service after changes constitutes acceptance of the new terms.
        </Section>

        <Section title="12. Contact">
          Questions about these terms? Email us at: <a href="mailto:legal@still.com" style={s.link}>legal@still.com</a>
        </Section>
      </main>
    </div>
  );
}

function Section({ title, children }) {
  return (
    <section style={{ marginBottom: 32 }}>
      <h2 style={{ fontFamily: "'Instrument Serif', serif", fontSize: 20, color: "#ffd6e7", marginBottom: 12, fontWeight: 400 }}>{title}</h2>
      <div style={{ fontSize: 13, color: "rgba(255,180,210,0.55)", lineHeight: 1.8 }}>{children}</div>
    </section>
  );
}

const s = {
  root: { minHeight: "100vh", background: "#0d0810" },
  nav: { padding: "20px 40px", borderBottom: "1px solid rgba(255,100,160,0.08)" },
  logo: { fontFamily: "'Instrument Serif', serif", fontSize: 17, color: "#ffd6e7" },
  main: { maxWidth: 680, margin: "0 auto", padding: "60px 24px" },
  title: { fontFamily: "'Instrument Serif', serif", fontSize: 38, color: "#ffd6e7", fontWeight: 400, marginBottom: 8 },
  date: { fontSize: 11, color: "rgba(255,180,210,0.3)", marginBottom: 48, letterSpacing: "0.04em" },
  list: { paddingLeft: 20, marginTop: 8, display: "flex", flexDirection: "column", gap: 6 },
  link: { color: "#ff9dc6" },
};
